"""
Custom Strategy Executor
========================

Executes custom strategies by evaluating conditions against market data.
Supports all indicator calculations and complex condition logic.
"""

import logging
import numpy as np
import pandas as pd
from datetime import datetime, timezone
from typing import Dict, List, Any, Optional, Tuple
from dataclasses import dataclass

from custom_strategy_service import (
    CustomStrategy, ConditionGroup, IndicatorCondition,
    ComparisonOperator, LogicalOperator, SignalDirection,
    AVAILABLE_INDICATORS
)

logger = logging.getLogger(__name__)


@dataclass
class StrategySignal:
    """Signal generated by custom strategy"""
    strategy_id: str
    strategy_name: str
    direction: SignalDirection
    confidence: float
    asset: str
    timeframe: str
    conditions_met: List[str]
    indicator_values: Dict[str, Any]
    timestamp: datetime
    
    def to_dict(self) -> Dict:
        return {
            "strategy_id": self.strategy_id,
            "strategy_name": self.strategy_name,
            "direction": self.direction.value,
            "confidence": self.confidence,
            "asset": self.asset,
            "timeframe": self.timeframe,
            "conditions_met": self.conditions_met,
            "indicator_values": self.indicator_values,
            "timestamp": self.timestamp.isoformat()
        }


class IndicatorCalculator:
    """Calculate indicator values from price data"""
    
    def __init__(self):
        self._cache = {}
    
    def calculate(self, indicator: str, parameters: Dict[str, Any], 
                  ohlcv_data: Dict[str, List[float]], output: str = "value") -> Optional[float]:
        """
        Calculate indicator value.
        
        Args:
            indicator: Indicator name (e.g., "RSI")
            parameters: Indicator parameters
            ohlcv_data: Dict with 'open', 'high', 'low', 'close', 'volume' lists
            output: Which output to return for multi-output indicators
        
        Returns:
            The calculated indicator value or None if calculation fails
        """
        try:
            closes = ohlcv_data.get("close", [])
            highs = ohlcv_data.get("high", [])
            lows = ohlcv_data.get("low", [])
            opens = ohlcv_data.get("open", [])
            volumes = ohlcv_data.get("volume", [])
            
            if not closes or len(closes) < 2:
                return None
            
            # Calculate based on indicator type
            if indicator == "RSI":
                return self._calculate_rsi(closes, parameters.get("period", 14))
            
            elif indicator == "SMA":
                return self._calculate_sma(closes, parameters.get("period", 14))
            
            elif indicator == "EMA":
                return self._calculate_ema(closes, parameters.get("period", 14))
            
            elif indicator == "MACD":
                result = self._calculate_macd(
                    closes,
                    parameters.get("fast_period", 12),
                    parameters.get("slow_period", 26),
                    parameters.get("signal_period", 9)
                )
                return result.get(output, result.get("macd_line"))
            
            elif indicator == "BOLLINGER_BANDS":
                result = self._calculate_bollinger(
                    closes,
                    parameters.get("period", 20),
                    parameters.get("std_dev", 2.0)
                )
                return result.get(output, result.get("middle"))
            
            elif indicator == "STOCHASTIC":
                result = self._calculate_stochastic(
                    highs, lows, closes,
                    parameters.get("k_period", 14),
                    parameters.get("d_period", 3),
                    parameters.get("slowing", 3)
                )
                return result.get(output, result.get("k"))
            
            elif indicator == "CCI":
                return self._calculate_cci(highs, lows, closes, parameters.get("period", 20))
            
            elif indicator == "ATR":
                return self._calculate_atr(highs, lows, closes, parameters.get("period", 14))
            
            elif indicator == "WILLIAMS_R":
                return self._calculate_williams_r(highs, lows, closes, parameters.get("period", 14))
            
            elif indicator == "MOM":
                return self._calculate_momentum(closes, parameters.get("period", 10))
            
            elif indicator == "ROC":
                return self._calculate_roc(closes, parameters.get("period", 10))
            
            elif indicator == "ADX":
                result = self._calculate_adx(highs, lows, closes, parameters.get("period", 14))
                return result.get(output, result.get("adx"))
            
            elif indicator == "AO":
                return self._calculate_ao(
                    highs, lows,
                    parameters.get("fast_period", 5),
                    parameters.get("slow_period", 34)
                )
            
            elif indicator == "SUPERTREND":
                result = self._calculate_supertrend(
                    highs, lows, closes,
                    parameters.get("period", 10),
                    parameters.get("multiplier", 3.0)
                )
                return result.get(output, result.get("direction"))
            
            elif indicator == "PRICE":
                price_type = parameters.get("type", "close")
                if price_type == "close":
                    return closes[-1]
                elif price_type == "open":
                    return opens[-1] if opens else closes[-1]
                elif price_type == "high":
                    return highs[-1] if highs else closes[-1]
                elif price_type == "low":
                    return lows[-1] if lows else closes[-1]
                elif price_type == "hl2":
                    return (highs[-1] + lows[-1]) / 2 if highs and lows else closes[-1]
                elif price_type == "hlc3":
                    return (highs[-1] + lows[-1] + closes[-1]) / 3 if highs and lows else closes[-1]
                elif price_type == "ohlc4":
                    return (opens[-1] + highs[-1] + lows[-1] + closes[-1]) / 4 if opens and highs and lows else closes[-1]
                return closes[-1]
            
            elif indicator == "VOLUME":
                return volumes[-1] if volumes else 0
            
            elif indicator == "OBV":
                return self._calculate_obv(closes, volumes)
            
            elif indicator == "MFI":
                return self._calculate_mfi(highs, lows, closes, volumes, parameters.get("period", 14))
            
            elif indicator == "KELTNER_CHANNEL":
                result = self._calculate_keltner(
                    highs, lows, closes,
                    parameters.get("ema_period", 20),
                    parameters.get("atr_period", 10),
                    parameters.get("multiplier", 1.5)
                )
                return result.get(output, result.get("middle"))
            
            elif indicator == "DONCHIAN_CHANNEL":
                result = self._calculate_donchian(highs, lows, parameters.get("period", 20))
                return result.get(output, result.get("middle"))
            
            elif indicator == "WMA":
                return self._calculate_wma(closes, parameters.get("period", 14))
            
            elif indicator == "VWAP":
                return self._calculate_vwap(highs, lows, closes, volumes)
            
            elif indicator == "STANDARD_DEVIATION":
                return self._calculate_stddev(closes, parameters.get("period", 20))
            
            elif indicator == "AROON":
                result = self._calculate_aroon(highs, lows, parameters.get("period", 25))
                return result.get(output, result.get("oscillator"))
            
            elif indicator == "AWESOME_OSCILLATOR":
                return self._calculate_ao(
                    highs, lows,
                    parameters.get("fast_period", 5),
                    parameters.get("slow_period", 34)
                )
            
            elif indicator == "DEMARKER":
                return self._calculate_demarker(highs, lows, parameters.get("period", 14))
            
            elif indicator == "OSMA":
                return self._calculate_osma(
                    closes,
                    parameters.get("fast_period", 12),
                    parameters.get("slow_period", 26),
                    parameters.get("signal_period", 9)
                )
            
            elif indicator == "VORTEX":
                result = self._calculate_vortex(highs, lows, closes, parameters.get("period", 14))
                return result.get(output, result.get("vi_plus"))
            
            elif indicator == "ENVELOPES":
                result = self._calculate_envelopes(
                    closes,
                    parameters.get("period", 14),
                    parameters.get("deviation", 0.1)
                )
                return result.get(output, result.get("middle"))
            
            elif indicator == "ALLIGATOR":
                result = self._calculate_alligator(
                    highs, lows,
                    parameters.get("jaws_period", 13),
                    parameters.get("teeth_period", 8),
                    parameters.get("lips_period", 5)
                )
                return result.get(output, result.get("lips"))
            
            elif indicator == "FRACTAL":
                result = self._calculate_fractal(highs, lows, parameters.get("period", 2))
                return result.get(output, result.get("up_fractal"))
            
            elif indicator == "BULLS_POWER":
                return self._calculate_bulls_power(highs, closes, parameters.get("period", 13))
            
            elif indicator == "BEARS_POWER":
                return self._calculate_bears_power(lows, closes, parameters.get("period", 13))
            
            elif indicator == "ZIGZAG":
                result = self._calculate_zigzag(
                    highs, lows,
                    parameters.get("depth", 12),
                    parameters.get("deviation", 5.0)
                )
                return result.get(output, result.get("last_pivot"))
            
            elif indicator == "HEIKIN_ASHI":
                result = self._calculate_heikin_ashi(opens, highs, lows, closes)
                return result.get(output, result.get("ha_close"))
            
            else:
                logger.warning(f"Unknown indicator: {indicator}")
                return None
                
        except Exception as e:
            logger.error(f"Error calculating {indicator}: {e}")
            return None
    
    def _calculate_rsi(self, prices: List[float], period: int) -> float:
        """Calculate RSI"""
        if len(prices) < period + 1:
            return 50.0
        
        prices_array = np.array(prices)
        deltas = np.diff(prices_array)
        gains = np.where(deltas > 0, deltas, 0)
        losses = np.where(deltas < 0, -deltas, 0)
        
        avg_gains = np.mean(gains[-period:])
        avg_losses = np.mean(losses[-period:])
        
        if avg_losses == 0:
            return 100.0
        
        rs = avg_gains / avg_losses
        return 100 - (100 / (1 + rs))
    
    def _calculate_sma(self, prices: List[float], period: int) -> float:
        """Calculate Simple Moving Average"""
        if len(prices) < period:
            return np.mean(prices) if prices else 0.0
        return np.mean(prices[-period:])
    
    def _calculate_ema(self, prices: List[float], period: int) -> float:
        """Calculate Exponential Moving Average"""
        if len(prices) < period:
            return np.mean(prices) if prices else 0.0
        
        series = pd.Series(prices)
        return series.ewm(span=period, adjust=False).mean().iloc[-1]
    
    def _calculate_macd(self, prices: List[float], fast: int, slow: int, signal: int) -> Dict[str, float]:
        """Calculate MACD"""
        if len(prices) < slow:
            return {"macd_line": 0.0, "signal_line": 0.0, "histogram": 0.0}
        
        series = pd.Series(prices)
        ema_fast = series.ewm(span=fast, adjust=False).mean()
        ema_slow = series.ewm(span=slow, adjust=False).mean()
        macd_line = ema_fast - ema_slow
        signal_line = macd_line.ewm(span=signal, adjust=False).mean()
        histogram = macd_line - signal_line
        
        return {
            "macd_line": macd_line.iloc[-1],
            "signal_line": signal_line.iloc[-1],
            "histogram": histogram.iloc[-1]
        }
    
    def _calculate_bollinger(self, prices: List[float], period: int, std_dev: float) -> Dict[str, float]:
        """Calculate Bollinger Bands"""
        if len(prices) < period:
            price = prices[-1] if prices else 0.0
            return {"upper": price, "middle": price, "lower": price, "bandwidth": 0.0, "percent_b": 0.5}
        
        series = pd.Series(prices)
        middle = series.rolling(period).mean().iloc[-1]
        std = series.rolling(period).std().iloc[-1]
        upper = middle + (std * std_dev)
        lower = middle - (std * std_dev)
        bandwidth = (upper - lower) / middle if middle != 0 else 0.0
        percent_b = (prices[-1] - lower) / (upper - lower) if (upper - lower) != 0 else 0.5
        
        return {
            "upper": upper,
            "middle": middle,
            "lower": lower,
            "bandwidth": bandwidth,
            "percent_b": percent_b
        }
    
    def _calculate_stochastic(self, highs: List[float], lows: List[float], closes: List[float],
                             k_period: int, d_period: int, slowing: int) -> Dict[str, float]:
        """Calculate Stochastic Oscillator"""
        if len(closes) < k_period:
            return {"k": 50.0, "d": 50.0}
        
        # Calculate %K
        high_max = max(highs[-k_period:])
        low_min = min(lows[-k_period:])
        
        if high_max == low_min:
            k = 50.0
        else:
            k = ((closes[-1] - low_min) / (high_max - low_min)) * 100
        
        # %D is SMA of %K (simplified)
        d = k  # In full implementation, would track %K history
        
        return {"k": k, "d": d}
    
    def _calculate_cci(self, highs: List[float], lows: List[float], closes: List[float], period: int) -> float:
        """Calculate CCI"""
        if len(closes) < period:
            return 0.0
        
        typical = [(h + l + c) / 3 for h, l, c in zip(highs[-period:], lows[-period:], closes[-period:])]
        sma = np.mean(typical)
        mean_dev = np.mean([abs(t - sma) for t in typical])
        
        if mean_dev == 0:
            return 0.0
        
        return (typical[-1] - sma) / (0.015 * mean_dev)
    
    def _calculate_atr(self, highs: List[float], lows: List[float], closes: List[float], period: int) -> float:
        """Calculate ATR"""
        if len(closes) < period + 1:
            return 0.0
        
        tr_list = []
        for i in range(-period, 0):
            tr = max(
                highs[i] - lows[i],
                abs(highs[i] - closes[i-1]),
                abs(lows[i] - closes[i-1])
            )
            tr_list.append(tr)
        
        return np.mean(tr_list)
    
    def _calculate_williams_r(self, highs: List[float], lows: List[float], closes: List[float], period: int) -> float:
        """Calculate Williams %R"""
        if len(closes) < period:
            return -50.0
        
        high_max = max(highs[-period:])
        low_min = min(lows[-period:])
        
        if high_max == low_min:
            return -50.0
        
        return ((high_max - closes[-1]) / (high_max - low_min)) * -100
    
    def _calculate_momentum(self, prices: List[float], period: int) -> float:
        """Calculate Momentum"""
        if len(prices) <= period:
            return 0.0
        return prices[-1] - prices[-period-1]
    
    def _calculate_roc(self, prices: List[float], period: int) -> float:
        """Calculate Rate of Change"""
        if len(prices) <= period or prices[-period-1] == 0:
            return 0.0
        return ((prices[-1] - prices[-period-1]) / prices[-period-1]) * 100
    
    def _calculate_adx(self, highs: List[float], lows: List[float], closes: List[float], period: int) -> Dict[str, float]:
        """Calculate ADX (simplified)"""
        if len(closes) < period * 2:
            return {"adx": 25.0, "plus_di": 0.0, "minus_di": 0.0}
        
        # Simplified ADX calculation
        atr = self._calculate_atr(highs, lows, closes, period)
        
        if atr == 0:
            return {"adx": 25.0, "plus_di": 0.0, "minus_di": 0.0}
        
        # Simplified DI calculation
        plus_dm = max(highs[-1] - highs[-2], 0)
        minus_dm = max(lows[-2] - lows[-1], 0)
        
        plus_di = (plus_dm / atr) * 100 if atr > 0 else 0
        minus_di = (minus_dm / atr) * 100 if atr > 0 else 0
        
        dx = abs(plus_di - minus_di) / (plus_di + minus_di) * 100 if (plus_di + minus_di) > 0 else 0
        adx = dx  # Simplified - would need smoothing in full implementation
        
        return {"adx": adx, "plus_di": plus_di, "minus_di": minus_di}
    
    def _calculate_ao(self, highs: List[float], lows: List[float], fast: int, slow: int) -> float:
        """Calculate Awesome Oscillator"""
        if len(highs) < slow:
            return 0.0
        
        midpoints = [(h + l) / 2 for h, l in zip(highs, lows)]
        fast_sma = np.mean(midpoints[-fast:])
        slow_sma = np.mean(midpoints[-slow:])
        
        return fast_sma - slow_sma
    
    def _calculate_supertrend(self, highs: List[float], lows: List[float], closes: List[float],
                              period: int, multiplier: float) -> Dict[str, Any]:
        """Calculate SuperTrend (simplified)"""
        if len(closes) < period:
            return {"value": closes[-1] if closes else 0, "direction": 1}
        
        atr = self._calculate_atr(highs, lows, closes, period)
        hl2 = (highs[-1] + lows[-1]) / 2
        
        upper = hl2 + (multiplier * atr)
        lower = hl2 - (multiplier * atr)
        
        # Simplified direction (would need history for proper calculation)
        direction = 1 if closes[-1] > lower else -1
        value = lower if direction == 1 else upper
        
        return {"value": value, "direction": direction}
    
    def _calculate_obv(self, closes: List[float], volumes: List[float]) -> float:
        """Calculate On-Balance Volume"""
        if len(closes) < 2 or not volumes:
            return 0.0
        
        obv = 0
        for i in range(1, min(len(closes), len(volumes))):
            if closes[i] > closes[i-1]:
                obv += volumes[i]
            elif closes[i] < closes[i-1]:
                obv -= volumes[i]
        
        return obv
    
    def _calculate_mfi(self, highs: List[float], lows: List[float], closes: List[float],
                       volumes: List[float], period: int) -> float:
        """Calculate Money Flow Index"""
        if len(closes) < period + 1 or len(volumes) < period + 1:
            return 50.0
        
        typical = [(h + l + c) / 3 for h, l, c in zip(highs, lows, closes)]
        raw_mf = [t * v for t, v in zip(typical, volumes)]
        
        pos_mf = 0
        neg_mf = 0
        
        for i in range(-period, 0):
            if typical[i] > typical[i-1]:
                pos_mf += raw_mf[i]
            else:
                neg_mf += raw_mf[i]
        
        if neg_mf == 0:
            return 100.0
        
        mfr = pos_mf / neg_mf
        return 100 - (100 / (1 + mfr))
    
    def _calculate_keltner(self, highs: List[float], lows: List[float], closes: List[float],
                           ema_period: int, atr_period: int, multiplier: float) -> Dict[str, float]:
        """Calculate Keltner Channel"""
        middle = self._calculate_ema(closes, ema_period)
        atr = self._calculate_atr(highs, lows, closes, atr_period)
        
        return {
            "upper": middle + (atr * multiplier),
            "middle": middle,
            "lower": middle - (atr * multiplier)
        }
    
    def _calculate_donchian(self, highs: List[float], lows: List[float], period: int) -> Dict[str, float]:
        """Calculate Donchian Channel"""
        if len(highs) < period:
            return {"upper": 0, "middle": 0, "lower": 0}
        
        upper = max(highs[-period:])
        lower = min(lows[-period:])
        middle = (upper + lower) / 2
        
        return {"upper": upper, "middle": middle, "lower": lower}
    
    # ============================================================
    # POCKET OPTION NATIVE INDICATORS
    # ============================================================
    
    def _calculate_wma(self, prices: List[float], period: int) -> float:
        """Calculate Weighted Moving Average"""
        if len(prices) < period:
            return np.mean(prices) if prices else 0.0
        recent = prices[-period:]
        weights = np.arange(1, period + 1)
        return float(np.sum(np.array(recent) * weights) / weights.sum())
    
    def _calculate_vwap(self, highs: List[float], lows: List[float],
                        closes: List[float], volumes: List[float]) -> float:
        """Calculate Volume Weighted Average Price (session-cumulative)"""
        if not closes or not volumes:
            return closes[-1] if closes else 0.0
        n = min(len(closes), len(volumes), len(highs), len(lows))
        if n == 0:
            return 0.0
        typical = [(highs[i] + lows[i] + closes[i]) / 3 for i in range(n)]
        cum_pv = sum(typical[i] * volumes[i] for i in range(n))
        cum_v = sum(volumes[:n])
        return cum_pv / cum_v if cum_v > 0 else closes[-1]
    
    def _calculate_stddev(self, prices: List[float], period: int) -> float:
        """Calculate Standard Deviation"""
        if len(prices) < period:
            return 0.0
        return float(np.std(prices[-period:], ddof=0))
    
    def _calculate_aroon(self, highs: List[float], lows: List[float], period: int) -> Dict[str, float]:
        """Calculate Aroon Up/Down/Oscillator"""
        if len(highs) < period + 1:
            return {"aroon_up": 50.0, "aroon_down": 50.0, "oscillator": 0.0}
        recent_h = highs[-(period + 1):]
        recent_l = lows[-(period + 1):]
        # bars since highest high / lowest low
        idx_high = period - int(np.argmax(recent_h))
        idx_low = period - int(np.argmin(recent_l))
        aroon_up = ((period - idx_high) / period) * 100
        aroon_down = ((period - idx_low) / period) * 100
        return {
            "aroon_up": aroon_up,
            "aroon_down": aroon_down,
            "oscillator": aroon_up - aroon_down
        }
    
    def _calculate_demarker(self, highs: List[float], lows: List[float], period: int) -> float:
        """Calculate DeMarker indicator (0-1)"""
        if len(highs) < period + 1:
            return 0.5
        de_max = []
        de_min = []
        for i in range(-period, 0):
            de_max.append(max(highs[i] - highs[i - 1], 0))
            de_min.append(max(lows[i - 1] - lows[i], 0))
        sum_max = sum(de_max)
        sum_min = sum(de_min)
        denom = sum_max + sum_min
        if denom == 0:
            return 0.5
        return sum_max / denom
    
    def _calculate_osma(self, prices: List[float], fast: int, slow: int, signal: int) -> float:
        """Calculate OsMA (MACD - Signal Line)"""
        macd_data = self._calculate_macd(prices, fast, slow, signal)
        return macd_data.get("histogram", 0.0)
    
    def _calculate_vortex(self, highs: List[float], lows: List[float],
                          closes: List[float], period: int) -> Dict[str, float]:
        """Calculate Vortex Indicator"""
        if len(closes) < period + 1:
            return {"vi_plus": 1.0, "vi_minus": 1.0}
        vm_plus_sum = 0.0
        vm_minus_sum = 0.0
        tr_sum = 0.0
        for i in range(-period, 0):
            vm_plus_sum += abs(highs[i] - lows[i - 1])
            vm_minus_sum += abs(lows[i] - highs[i - 1])
            tr = max(
                highs[i] - lows[i],
                abs(highs[i] - closes[i - 1]),
                abs(lows[i] - closes[i - 1])
            )
            tr_sum += tr
        if tr_sum == 0:
            return {"vi_plus": 1.0, "vi_minus": 1.0}
        return {
            "vi_plus": vm_plus_sum / tr_sum,
            "vi_minus": vm_minus_sum / tr_sum
        }
    
    def _calculate_envelopes(self, prices: List[float], period: int,
                             deviation: float) -> Dict[str, float]:
        """Calculate Envelopes (% deviation around SMA)"""
        middle = self._calculate_sma(prices, period)
        dev = middle * (deviation / 100.0)
        return {
            "upper": middle + dev,
            "middle": middle,
            "lower": middle - dev
        }
    
    def _calculate_alligator(self, highs: List[float], lows: List[float],
                             jaws: int, teeth: int, lips: int) -> Dict[str, float]:
        """Calculate Bill Williams Alligator (SMMA on median price)"""
        if not highs or not lows:
            return {"jaws": 0.0, "teeth": 0.0, "lips": 0.0}
        median = [(h + l) / 2 for h, l in zip(highs, lows)]
        return {
            "jaws": self._smma(median, jaws),
            "teeth": self._smma(median, teeth),
            "lips": self._smma(median, lips)
        }
    
    def _smma(self, prices: List[float], period: int) -> float:
        """Smoothed Moving Average (used by Alligator)"""
        if len(prices) < period:
            return float(np.mean(prices)) if prices else 0.0
        # Initial SMMA = SMA
        smma = float(np.mean(prices[:period]))
        # Apply recursive smoothing
        for price in prices[period:]:
            smma = (smma * (period - 1) + price) / period
        return smma
    
    def _calculate_fractal(self, highs: List[float], lows: List[float],
                           period: int) -> Dict[str, float]:
        """Williams Fractal: bar is up-fractal if highest in 2*period+1 window"""
        n = 2 * period + 1
        if len(highs) < n:
            return {"up_fractal": 0.0, "down_fractal": 0.0, "last_pivot": 0.0}
        # Check the bar at position -(period+1) (center of last full window)
        center_idx = -(period + 1)
        center_high = highs[center_idx]
        center_low = lows[center_idx]
        window_h = highs[-n:]
        window_l = lows[-n:]
        is_up_fractal = 1.0 if center_high == max(window_h) else 0.0
        is_down_fractal = 1.0 if center_low == min(window_l) else 0.0
        return {
            "up_fractal": is_up_fractal,
            "down_fractal": is_down_fractal,
            "last_pivot": center_high if is_up_fractal else (center_low if is_down_fractal else 0.0)
        }
    
    def _calculate_bulls_power(self, highs: List[float], closes: List[float],
                               period: int) -> float:
        """Bulls Power = High - EMA(close)"""
        if not highs:
            return 0.0
        ema = self._calculate_ema(closes, period)
        return highs[-1] - ema
    
    def _calculate_bears_power(self, lows: List[float], closes: List[float],
                               period: int) -> float:
        """Bears Power = Low - EMA(close)"""
        if not lows:
            return 0.0
        ema = self._calculate_ema(closes, period)
        return lows[-1] - ema
    
    def _calculate_zigzag(self, highs: List[float], lows: List[float],
                          depth: int, deviation: float) -> Dict[str, float]:
        """Simplified ZigZag - returns last detected pivot"""
        if len(highs) < depth + 1:
            return {"last_pivot": 0.0, "is_high": 0.0, "is_low": 0.0}
        recent_h = highs[-depth:]
        recent_l = lows[-depth:]
        last_high = max(recent_h)
        last_low = min(recent_l)
        # Check if current bar is a pivot
        cur_h = highs[-1]
        cur_l = lows[-1]
        is_high = 1.0 if cur_h == last_high else 0.0
        is_low = 1.0 if cur_l == last_low else 0.0
        # Apply deviation filter
        range_pct = ((last_high - last_low) / last_low * 100) if last_low > 0 else 0
        if range_pct < deviation:
            is_high = is_low = 0.0
        return {
            "last_pivot": last_high if is_high else (last_low if is_low else 0.0),
            "is_high": is_high,
            "is_low": is_low
        }
    
    def _calculate_heikin_ashi(self, opens: List[float], highs: List[float],
                                lows: List[float], closes: List[float]) -> Dict[str, float]:
        """Calculate latest Heikin Ashi candle (HA) values"""
        if not closes or not opens or not highs or not lows:
            return {"ha_open": 0.0, "ha_high": 0.0, "ha_low": 0.0, "ha_close": 0.0, "is_green": 0.0}
        # HA Close = (O+H+L+C)/4
        ha_close = (opens[-1] + highs[-1] + lows[-1] + closes[-1]) / 4
        # HA Open = (prev_HA_Open + prev_HA_Close)/2  (use raw OHLC for first bar)
        if len(opens) >= 2:
            prev_ha_close = (opens[-2] + highs[-2] + lows[-2] + closes[-2]) / 4
            prev_ha_open = (opens[-2] + closes[-2]) / 2  # simplified seed
            ha_open = (prev_ha_open + prev_ha_close) / 2
        else:
            ha_open = (opens[-1] + closes[-1]) / 2
        ha_high = max(highs[-1], ha_open, ha_close)
        ha_low = min(lows[-1], ha_open, ha_close)
        return {
            "ha_open": ha_open,
            "ha_high": ha_high,
            "ha_low": ha_low,
            "ha_close": ha_close,
            "is_green": 1.0 if ha_close > ha_open else 0.0
        }


class CustomStrategyExecutor:
    """Execute custom strategies against market data"""
    
    def __init__(self):
        self.calculator = IndicatorCalculator()
        self._previous_values: Dict[str, Dict[str, float]] = {}  # For crossover detection
    
    def evaluate_strategy(self, strategy: Dict[str, Any], ohlcv_data: Dict[str, List[float]],
                          asset: str, timeframe: str) -> Optional[StrategySignal]:
        """
        Evaluate a strategy against current market data.
        
        Args:
            strategy: Strategy definition dict
            ohlcv_data: OHLCV market data
            asset: Asset symbol
            timeframe: Current timeframe
        
        Returns:
            StrategySignal if conditions are met, None otherwise
        """
        try:
            indicator_values = {}
            
            # Check CALL conditions
            call_met, call_conditions = self._evaluate_condition_groups(
                strategy.get("call_conditions", []),
                ohlcv_data,
                indicator_values
            )
            
            # Check PUT conditions
            put_met, put_conditions = self._evaluate_condition_groups(
                strategy.get("put_conditions", []),
                ohlcv_data,
                indicator_values
            )
            
            # Determine signal
            if call_met and not put_met:
                direction = SignalDirection.CALL
                conditions_met = call_conditions
                confidence = self._calculate_confidence(strategy, call_conditions)
            elif put_met and not call_met:
                direction = SignalDirection.PUT
                conditions_met = put_conditions
                confidence = self._calculate_confidence(strategy, put_conditions)
            else:
                # No clear signal (both or neither)
                return None
            
            # Check minimum confidence
            if confidence < strategy.get("min_confidence", 75.0):
                return None
            
            return StrategySignal(
                strategy_id=strategy["id"],
                strategy_name=strategy["name"],
                direction=direction,
                confidence=confidence,
                asset=asset,
                timeframe=timeframe,
                conditions_met=conditions_met,
                indicator_values=indicator_values,
                timestamp=datetime.now(timezone.utc)
            )
            
        except Exception as e:
            logger.error(f"Error evaluating strategy {strategy.get('name')}: {e}")
            return None
    
    def _evaluate_condition_groups(self, groups: List[Dict], ohlcv_data: Dict[str, List[float]],
                                    indicator_values: Dict[str, Any]) -> Tuple[bool, List[str]]:
        """
        Evaluate all condition groups.
        
        Returns:
            Tuple of (all_groups_met, list_of_met_conditions)
        """
        if not groups:
            return False, []
        
        all_met = True
        met_conditions = []
        
        for group in groups:
            group_met, group_conditions = self._evaluate_single_group(group, ohlcv_data, indicator_values)
            
            if group_met:
                met_conditions.extend(group_conditions)
            else:
                all_met = False
        
        return all_met, met_conditions
    
    def _evaluate_single_group(self, group: Dict, ohlcv_data: Dict[str, List[float]],
                                indicator_values: Dict[str, Any]) -> Tuple[bool, List[str]]:
        """
        Evaluate a single condition group with AND/OR logic.
        """
        conditions = group.get("conditions", [])
        logical_op = group.get("logical_operator", "AND")
        
        if not conditions:
            return False, []
        
        met_conditions = []
        results = []
        
        for condition in conditions:
            met, description = self._evaluate_condition(condition, ohlcv_data, indicator_values)
            results.append(met)
            if met:
                met_conditions.append(description)
        
        if logical_op == "AND":
            return all(results), met_conditions
        else:  # OR
            return any(results), met_conditions
    
    def _evaluate_condition(self, condition: Dict, ohlcv_data: Dict[str, List[float]],
                            indicator_values: Dict[str, Any]) -> Tuple[bool, str]:
        """
        Evaluate a single condition.
        
        Returns:
            Tuple of (condition_met, description)
        """
        try:
            indicator = condition.get("indicator")
            parameters = condition.get("parameters", {})
            output = condition.get("output", "value")
            operator = condition.get("operator")
            compare_to = condition.get("compare_to")
            compare_value = condition.get("compare_value")
            
            # Calculate indicator value
            ind_value = self.calculator.calculate(indicator, parameters, ohlcv_data, output)
            
            if ind_value is None:
                return False, ""
            
            # Store in indicator values
            ind_key = f"{indicator}_{output}_{json.dumps(parameters, sort_keys=True)}" if parameters else f"{indicator}_{output}"
            indicator_values[ind_key] = ind_value
            
            # Get comparison value
            if compare_to == "value":
                comp_value = float(compare_value)
            elif compare_to == "indicator":
                # compare_value is another indicator config
                comp_config = compare_value
                comp_value = self.calculator.calculate(
                    comp_config.get("indicator"),
                    comp_config.get("parameters", {}),
                    ohlcv_data,
                    comp_config.get("output", "value")
                )
                if comp_value is None:
                    return False, ""
            elif compare_to == "previous":
                # Compare to previous value of same indicator
                prev_key = f"prev_{ind_key}"
                comp_value = self._previous_values.get(prev_key, ind_value)
                self._previous_values[prev_key] = ind_value
            else:
                comp_value = float(compare_value)
            
            # Evaluate comparison
            met = self._compare_values(ind_value, comp_value, operator, ohlcv_data, indicator, parameters, output)
            
            description = f"{indicator}({output}) {operator} {comp_value:.4f}" if met else ""
            
            return met, description
            
        except Exception as e:
            logger.error(f"Error evaluating condition: {e}")
            return False, ""
    
    def _compare_values(self, value1: float, value2: float, operator: str,
                        ohlcv_data: Dict = None, indicator: str = None,
                        parameters: Dict = None, output: str = "value") -> bool:
        """Compare two values with the given operator"""
        try:
            if operator == ">" or operator == "GREATER_THAN":
                return value1 > value2
            elif operator == "<" or operator == "LESS_THAN":
                return value1 < value2
            elif operator == "=" or operator == "EQUAL":
                return abs(value1 - value2) < 0.0001
            elif operator == ">=" or operator == "GREATER_EQUAL":
                return value1 >= value2
            elif operator == "<=" or operator == "LESS_EQUAL":
                return value1 <= value2
            elif operator == "crosses_above" or operator == "CROSSES_ABOVE":
                # Need previous values to detect crossover
                key = f"prev_{indicator}_{output}"
                prev = self._previous_values.get(key)
                self._previous_values[key] = value1
                if prev is not None:
                    return prev <= value2 and value1 > value2
                return False
            elif operator == "crosses_below" or operator == "CROSSES_BELOW":
                key = f"prev_{indicator}_{output}"
                prev = self._previous_values.get(key)
                self._previous_values[key] = value1
                if prev is not None:
                    return prev >= value2 and value1 < value2
                return False
            elif operator == "between" or operator == "BETWEEN":
                if isinstance(value2, (list, tuple)) and len(value2) >= 2:
                    return value2[0] <= value1 <= value2[1]
                return False
            elif operator == "not_between" or operator == "NOT_BETWEEN":
                if isinstance(value2, (list, tuple)) and len(value2) >= 2:
                    return value1 < value2[0] or value1 > value2[1]
                return False
            else:
                logger.warning(f"Unknown operator: {operator}")
                return False
        except Exception as e:
            logger.error(f"Error comparing values: {e}")
            return False
    
    def _calculate_confidence(self, strategy: Dict, met_conditions: List[str]) -> float:
        """Calculate signal confidence based on met conditions"""
        # Base confidence starts at 75
        base_confidence = 75.0
        
        # Add confidence for each met condition
        num_conditions = len(met_conditions)
        confidence_boost = min(num_conditions * 5, 20)  # Max 20% boost
        
        return min(base_confidence + confidence_boost, 99.0)


import json

# Global executor instance
_executor: Optional[CustomStrategyExecutor] = None


def get_strategy_executor() -> CustomStrategyExecutor:
    """Get or create strategy executor"""
    global _executor
    if _executor is None:
        _executor = CustomStrategyExecutor()
    return _executor
