"""
Enhanced AI/ML Trading System
=============================
Comprehensive AI-powered trading system combining:

1. TREND FOLLOWING - Early detection of emerging trends using ML
2. MEAN REVERSION - Identifying overbought/oversold conditions
3. PATTERN RECOGNITION - Neural networks for price pattern detection
4. CONTINUOUS LEARNING - Models improve from trade outcomes
5. CUSTOM STRATEGY INTEGRATION - Execute user-built strategies

This system processes market data 24/7 and adapts to changing conditions.
"""

import os
os.environ['CUDA_VISIBLE_DEVICES'] = '-1'
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

import numpy as np
import pandas as pd
import asyncio
import logging
import json
from datetime import datetime, timezone, timedelta
from typing import Dict, List, Optional, Tuple, Any, Callable
from dataclasses import dataclass, field
from enum import Enum
from collections import deque
import pickle

# ML Libraries
try:
    from sklearn.preprocessing import StandardScaler, MinMaxScaler
    from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, VotingClassifier
    from sklearn.model_selection import TimeSeriesSplit
    from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
    from sklearn.neural_network import MLPClassifier
    SKLEARN_AVAILABLE = True
except ImportError:
    SKLEARN_AVAILABLE = False
    logging.warning("sklearn not available - ML features disabled")

logger = logging.getLogger(__name__)


class TradingDirection(Enum):
    """Trading signal direction"""
    CALL = "CALL"
    PUT = "PUT"
    HOLD = "HOLD"


class MarketRegime(Enum):
    """Market regime classification"""
    TRENDING_UP = "TRENDING_UP"
    TRENDING_DOWN = "TRENDING_DOWN"
    RANGING = "RANGING"
    VOLATILE = "VOLATILE"
    CALM = "CALM"


class StrategyType(Enum):
    """Type of trading strategy"""
    TREND_FOLLOWING = "trend_following"
    MEAN_REVERSION = "mean_reversion"
    MOMENTUM = "momentum"
    BREAKOUT = "breakout"
    SCALPING = "scalping"
    CUSTOM = "custom"


@dataclass
class MLSignal:
    """Signal generated by ML model"""
    direction: TradingDirection
    confidence: float  # 0-100
    strategy_type: StrategyType
    model_name: str
    reasoning: str
    features_used: List[str] = field(default_factory=list)
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    
    def to_dict(self) -> Dict:
        return {
            "direction": self.direction.value,
            "confidence": self.confidence,
            "strategy_type": self.strategy_type.value,
            "model_name": self.model_name,
            "reasoning": self.reasoning,
            "features_used": self.features_used,
            "timestamp": self.timestamp.isoformat()
        }


@dataclass
class EnsembleSignal:
    """Combined signal from multiple ML models"""
    final_direction: TradingDirection
    final_confidence: float
    consensus_score: float  # How much models agree (0-1)
    individual_signals: List[MLSignal]
    market_regime: MarketRegime
    risk_level: str  # LOW, MEDIUM, HIGH
    recommended_expiry: str  # Suggested expiration time
    
    def to_dict(self) -> Dict:
        return {
            "final_direction": self.final_direction.value,
            "final_confidence": self.final_confidence,
            "consensus_score": self.consensus_score,
            "individual_signals": [s.to_dict() for s in self.individual_signals],
            "market_regime": self.market_regime.value,
            "risk_level": self.risk_level,
            "recommended_expiry": self.recommended_expiry
        }


class FeatureEngineering:
    """
    Feature engineering for ML models.
    Creates comprehensive feature sets for trading prediction.
    """
    
    @staticmethod
    def calculate_returns(prices: np.ndarray, periods: List[int] = [1, 5, 10, 20]) -> Dict[str, np.ndarray]:
        """Calculate returns over various periods"""
        returns = {}
        for period in periods:
            if len(prices) > period:
                returns[f"return_{period}"] = (prices[period:] - prices[:-period]) / prices[:-period]
        return returns
    
    @staticmethod
    def calculate_volatility(prices: np.ndarray, window: int = 20) -> np.ndarray:
        """Calculate rolling volatility"""
        returns = np.diff(prices) / prices[:-1]
        volatility = pd.Series(returns).rolling(window).std().values
        return volatility
    
    @staticmethod
    def calculate_momentum(prices: np.ndarray, period: int = 14) -> np.ndarray:
        """Calculate momentum indicator"""
        if len(prices) < period:
            return np.zeros(len(prices))
        momentum = prices[period:] - prices[:-period]
        return np.concatenate([np.zeros(period), momentum])
    
    @staticmethod
    def calculate_rsi(prices: np.ndarray, period: int = 14) -> np.ndarray:
        """Calculate RSI"""
        delta = np.diff(prices)
        gain = np.where(delta > 0, delta, 0)
        loss = np.where(delta < 0, -delta, 0)
        
        avg_gain = pd.Series(gain).rolling(period).mean().values
        avg_loss = pd.Series(loss).rolling(period).mean().values
        
        rs = np.where(avg_loss != 0, avg_gain / avg_loss, 0)
        rsi = 100 - (100 / (1 + rs))
        return np.concatenate([[50], rsi])
    
    @staticmethod
    def calculate_bollinger_position(prices: np.ndarray, period: int = 20, std_mult: float = 2.0) -> np.ndarray:
        """Calculate position within Bollinger Bands (-1 to 1)"""
        sma = pd.Series(prices).rolling(period).mean().values
        std = pd.Series(prices).rolling(period).std().values
        
        upper = sma + std_mult * std
        lower = sma - std_mult * std
        
        # Position: -1 at lower band, 0 at middle, 1 at upper band
        band_width = upper - lower
        position = np.where(band_width != 0, 
                          2 * (prices - lower) / band_width - 1,
                          0)
        return position
    
    @staticmethod
    def calculate_trend_strength(prices: np.ndarray, short_period: int = 10, long_period: int = 30) -> np.ndarray:
        """Calculate trend strength (-100 to 100)"""
        short_ma = pd.Series(prices).rolling(short_period).mean().values
        long_ma = pd.Series(prices).rolling(long_period).mean().values
        
        # Trend strength based on MA divergence
        strength = np.where(long_ma != 0,
                          100 * (short_ma - long_ma) / long_ma,
                          0)
        return np.clip(strength, -100, 100)
    
    @staticmethod
    def create_features(ohlcv_data: Dict[str, np.ndarray]) -> Tuple[np.ndarray, List[str]]:
        """
        Create comprehensive feature set from OHLCV data.
        
        Args:
            ohlcv_data: Dict with 'open', 'high', 'low', 'close', 'volume'
        
        Returns:
            Tuple of (features array, feature names)
        """
        closes = ohlcv_data.get('close', np.array([]))
        highs = ohlcv_data.get('high', np.array([]))
        lows = ohlcv_data.get('low', np.array([]))
        volumes = ohlcv_data.get('volume', np.array([]))
        
        if len(closes) < 50:
            return np.array([]), []
        
        features = []
        feature_names = []
        
        # Price-based features
        returns = FeatureEngineering.calculate_returns(closes)
        for name, values in returns.items():
            padded = np.concatenate([np.zeros(len(closes) - len(values)), values])
            features.append(padded)
            feature_names.append(name)
        
        # Volatility
        volatility = FeatureEngineering.calculate_volatility(closes)
        features.append(np.concatenate([[0], volatility]))
        feature_names.append("volatility_20")
        
        # Momentum
        momentum = FeatureEngineering.calculate_momentum(closes)
        features.append(momentum)
        feature_names.append("momentum_14")
        
        # RSI
        rsi = FeatureEngineering.calculate_rsi(closes)
        features.append(rsi)
        feature_names.append("rsi_14")
        
        # Bollinger position
        bb_pos = FeatureEngineering.calculate_bollinger_position(closes)
        features.append(bb_pos)
        feature_names.append("bb_position")
        
        # Trend strength
        trend = FeatureEngineering.calculate_trend_strength(closes)
        features.append(trend)
        feature_names.append("trend_strength")
        
        # High-Low range
        hl_range = (highs - lows) / closes
        features.append(hl_range)
        feature_names.append("hl_range")
        
        # Close position in range
        close_pos = np.where(highs != lows,
                           (closes - lows) / (highs - lows),
                           0.5)
        features.append(close_pos)
        feature_names.append("close_position")
        
        # Volume features (if available)
        if len(volumes) == len(closes) and np.any(volumes > 0):
            vol_ma = pd.Series(volumes).rolling(20).mean().values
            vol_ratio = np.where(vol_ma != 0, volumes / vol_ma, 1)
            features.append(vol_ratio)
            feature_names.append("volume_ratio")
        
        # Stack features
        feature_array = np.column_stack(features)
        
        # Remove NaN rows
        valid_mask = ~np.isnan(feature_array).any(axis=1)
        feature_array = feature_array[valid_mask]
        
        return feature_array, feature_names


class TrendFollowingModel:
    """
    AI model for early trend detection.
    Uses gradient boosting to identify emerging trends before they become obvious.
    """
    
    def __init__(self):
        self.model = GradientBoostingClassifier(
            n_estimators=100,
            max_depth=5,
            learning_rate=0.1,
            random_state=42
        ) if SKLEARN_AVAILABLE else None
        self.scaler = StandardScaler() if SKLEARN_AVAILABLE else None
        self.is_trained = False
        self.feature_names = []
        self.accuracy = 0.0
    
    def train(self, features: np.ndarray, labels: np.ndarray, feature_names: List[str]):
        """Train the trend following model"""
        if not SKLEARN_AVAILABLE or len(features) < 100:
            return False
        
        try:
            # Scale features
            features_scaled = self.scaler.fit_transform(features)
            
            # Train with time series split
            tscv = TimeSeriesSplit(n_splits=5)
            accuracies = []
            
            for train_idx, val_idx in tscv.split(features_scaled):
                X_train, X_val = features_scaled[train_idx], features_scaled[val_idx]
                y_train, y_val = labels[train_idx], labels[val_idx]
                
                self.model.fit(X_train, y_train)
                predictions = self.model.predict(X_val)
                accuracies.append(accuracy_score(y_val, predictions))
            
            self.accuracy = np.mean(accuracies)
            self.feature_names = feature_names
            self.is_trained = True
            
            logger.info(f"TrendFollowingModel trained with accuracy: {self.accuracy:.2%}")
            return True
            
        except Exception as e:
            logger.error(f"Error training TrendFollowingModel: {e}")
            return False
    
    def predict(self, features: np.ndarray) -> Optional[MLSignal]:
        """Generate trend following signal"""
        if not self.is_trained or not SKLEARN_AVAILABLE:
            return None
        
        try:
            features_scaled = self.scaler.transform(features.reshape(1, -1))
            prediction = self.model.predict(features_scaled)[0]
            probabilities = self.model.predict_proba(features_scaled)[0]
            
            confidence = max(probabilities) * 100
            
            if prediction == 1:  # Uptrend
                direction = TradingDirection.CALL
                reasoning = "Strong uptrend detected - momentum and MA alignment bullish"
            elif prediction == -1:  # Downtrend
                direction = TradingDirection.PUT
                reasoning = "Strong downtrend detected - momentum and MA alignment bearish"
            else:
                direction = TradingDirection.HOLD
                reasoning = "No clear trend - staying neutral"
            
            return MLSignal(
                direction=direction,
                confidence=confidence,
                strategy_type=StrategyType.TREND_FOLLOWING,
                model_name="TrendFollowingModel",
                reasoning=reasoning,
                features_used=self.feature_names[:5]
            )
            
        except Exception as e:
            logger.error(f"TrendFollowingModel prediction error: {e}")
            return None


class MeanReversionModel:
    """
    AI model for mean reversion trading.
    Identifies overbought/oversold conditions for reversal opportunities.
    """
    
    def __init__(self):
        self.model = RandomForestClassifier(
            n_estimators=100,
            max_depth=8,
            random_state=42
        ) if SKLEARN_AVAILABLE else None
        self.scaler = StandardScaler() if SKLEARN_AVAILABLE else None
        self.is_trained = False
        self.feature_names = []
        self.accuracy = 0.0
    
    def train(self, features: np.ndarray, labels: np.ndarray, feature_names: List[str]):
        """Train mean reversion model"""
        if not SKLEARN_AVAILABLE or len(features) < 100:
            return False
        
        try:
            features_scaled = self.scaler.fit_transform(features)
            
            tscv = TimeSeriesSplit(n_splits=5)
            accuracies = []
            
            for train_idx, val_idx in tscv.split(features_scaled):
                X_train, X_val = features_scaled[train_idx], features_scaled[val_idx]
                y_train, y_val = labels[train_idx], labels[val_idx]
                
                self.model.fit(X_train, y_train)
                predictions = self.model.predict(X_val)
                accuracies.append(accuracy_score(y_val, predictions))
            
            self.accuracy = np.mean(accuracies)
            self.feature_names = feature_names
            self.is_trained = True
            
            logger.info(f"MeanReversionModel trained with accuracy: {self.accuracy:.2%}")
            return True
            
        except Exception as e:
            logger.error(f"Error training MeanReversionModel: {e}")
            return False
    
    def predict(self, features: np.ndarray) -> Optional[MLSignal]:
        """Generate mean reversion signal"""
        if not self.is_trained or not SKLEARN_AVAILABLE:
            return None
        
        try:
            features_scaled = self.scaler.transform(features.reshape(1, -1))
            prediction = self.model.predict(features_scaled)[0]
            probabilities = self.model.predict_proba(features_scaled)[0]
            
            confidence = max(probabilities) * 100
            
            # Extract RSI and BB position from features for reasoning
            rsi_idx = self.feature_names.index("rsi_14") if "rsi_14" in self.feature_names else -1
            bb_idx = self.feature_names.index("bb_position") if "bb_position" in self.feature_names else -1
            
            rsi_val = features[rsi_idx] if rsi_idx >= 0 else 50
            bb_val = features[bb_idx] if bb_idx >= 0 else 0
            
            if prediction == 1:  # Mean reversion UP (from oversold)
                direction = TradingDirection.CALL
                reasoning = f"Oversold reversal - RSI={rsi_val:.1f}, BB position={bb_val:.2f}"
            elif prediction == -1:  # Mean reversion DOWN (from overbought)
                direction = TradingDirection.PUT
                reasoning = f"Overbought reversal - RSI={rsi_val:.1f}, BB position={bb_val:.2f}"
            else:
                direction = TradingDirection.HOLD
                reasoning = "Price near mean - no reversal expected"
            
            return MLSignal(
                direction=direction,
                confidence=confidence,
                strategy_type=StrategyType.MEAN_REVERSION,
                model_name="MeanReversionModel",
                reasoning=reasoning,
                features_used=["rsi_14", "bb_position", "volatility_20"]
            )
            
        except Exception as e:
            logger.error(f"MeanReversionModel prediction error: {e}")
            return None


class PatternRecognitionModel:
    """
    Neural network for price pattern recognition.
    Identifies complex patterns that traditional indicators miss.
    """
    
    def __init__(self):
        self.model = MLPClassifier(
            hidden_layer_sizes=(64, 32, 16),
            activation='relu',
            max_iter=500,
            random_state=42,
            early_stopping=True
        ) if SKLEARN_AVAILABLE else None
        self.scaler = StandardScaler() if SKLEARN_AVAILABLE else None
        self.is_trained = False
        self.feature_names = []
        self.accuracy = 0.0
    
    def train(self, features: np.ndarray, labels: np.ndarray, feature_names: List[str]):
        """Train pattern recognition neural network"""
        if not SKLEARN_AVAILABLE or len(features) < 200:
            return False
        
        try:
            features_scaled = self.scaler.fit_transform(features)
            
            tscv = TimeSeriesSplit(n_splits=5)
            accuracies = []
            
            for train_idx, val_idx in tscv.split(features_scaled):
                X_train, X_val = features_scaled[train_idx], features_scaled[val_idx]
                y_train, y_val = labels[train_idx], labels[val_idx]
                
                self.model.fit(X_train, y_train)
                predictions = self.model.predict(X_val)
                accuracies.append(accuracy_score(y_val, predictions))
            
            self.accuracy = np.mean(accuracies)
            self.feature_names = feature_names
            self.is_trained = True
            
            logger.info(f"PatternRecognitionModel trained with accuracy: {self.accuracy:.2%}")
            return True
            
        except Exception as e:
            logger.error(f"Error training PatternRecognitionModel: {e}")
            return False
    
    def predict(self, features: np.ndarray) -> Optional[MLSignal]:
        """Generate pattern-based signal"""
        if not self.is_trained or not SKLEARN_AVAILABLE:
            return None
        
        try:
            features_scaled = self.scaler.transform(features.reshape(1, -1))
            prediction = self.model.predict(features_scaled)[0]
            probabilities = self.model.predict_proba(features_scaled)[0]
            
            confidence = max(probabilities) * 100
            
            if prediction == 1:
                direction = TradingDirection.CALL
                reasoning = "Neural network detected bullish pattern formation"
            elif prediction == -1:
                direction = TradingDirection.PUT
                reasoning = "Neural network detected bearish pattern formation"
            else:
                direction = TradingDirection.HOLD
                reasoning = "No clear pattern detected"
            
            return MLSignal(
                direction=direction,
                confidence=confidence,
                strategy_type=StrategyType.MOMENTUM,
                model_name="PatternRecognitionModel",
                reasoning=reasoning,
                features_used=self.feature_names[:5]
            )
            
        except Exception as e:
            logger.error(f"PatternRecognitionModel prediction error: {e}")
            return None


class EnhancedAITradingSystem:
    """
    Main AI Trading System that combines all models.
    Provides ensemble predictions and continuous learning.
    """
    
    def __init__(self):
        self.trend_model = TrendFollowingModel()
        self.mean_reversion_model = MeanReversionModel()
        self.pattern_model = PatternRecognitionModel()
        
        # Training data storage
        self.training_data = deque(maxlen=10000)
        self.trade_results = deque(maxlen=1000)
        
        # Model states
        self.models_trained = False
        self.last_training_time = None
        self.total_trades = 0
        self.winning_trades = 0
        
        # Market regime detection
        self.current_regime = MarketRegime.CALM
        
        logger.info("EnhancedAITradingSystem initialized")
    
    def detect_market_regime(self, features: np.ndarray, feature_names: List[str]) -> MarketRegime:
        """Detect current market regime"""
        try:
            vol_idx = feature_names.index("volatility_20") if "volatility_20" in feature_names else -1
            trend_idx = feature_names.index("trend_strength") if "trend_strength" in feature_names else -1
            
            volatility = features[vol_idx] if vol_idx >= 0 else 0.01
            trend = features[trend_idx] if trend_idx >= 0 else 0
            
            # Classify regime
            if volatility > 0.02:  # High volatility
                return MarketRegime.VOLATILE
            elif abs(trend) > 50:
                return MarketRegime.TRENDING_UP if trend > 0 else MarketRegime.TRENDING_DOWN
            elif abs(trend) < 10:
                return MarketRegime.RANGING
            else:
                return MarketRegime.CALM
                
        except Exception as e:
            logger.error(f"Error detecting market regime: {e}")
            return MarketRegime.CALM
    
    def prepare_training_labels(self, closes: np.ndarray, lookahead: int = 5) -> np.ndarray:
        """
        Create training labels based on future price movement.
        
        Args:
            closes: Array of closing prices
            lookahead: Number of periods to look ahead
        
        Returns:
            Array of labels: 1 (up), -1 (down), 0 (neutral)
        """
        labels = np.zeros(len(closes))
        
        for i in range(len(closes) - lookahead):
            future_return = (closes[i + lookahead] - closes[i]) / closes[i]
            
            if future_return > 0.001:  # 0.1% threshold
                labels[i] = 1
            elif future_return < -0.001:
                labels[i] = -1
            else:
                labels[i] = 0
        
        return labels
    
    async def train_models(self, ohlcv_data: Dict[str, np.ndarray]) -> Dict[str, Any]:
        """
        Train all ML models with historical data.
        
        Args:
            ohlcv_data: Dict with 'open', 'high', 'low', 'close', 'volume'
        
        Returns:
            Training results summary
        """
        results = {
            "success": False,
            "models_trained": [],
            "accuracies": {},
            "training_samples": 0
        }
        
        try:
            # Create features
            features, feature_names = FeatureEngineering.create_features(ohlcv_data)
            if len(features) < 200:
                results["error"] = "Insufficient data for training"
                return results
            
            # Create labels
            closes = ohlcv_data.get('close', np.array([]))
            labels = self.prepare_training_labels(closes)
            
            # Align features and labels
            min_len = min(len(features), len(labels))
            features = features[:min_len]
            labels = labels[:min_len]
            
            # Remove samples with neutral labels for trend/mean reversion
            non_neutral_mask = labels != 0
            train_features = features[non_neutral_mask]
            train_labels = labels[non_neutral_mask]
            
            results["training_samples"] = len(train_features)
            
            # Train each model
            if self.trend_model.train(train_features, train_labels, feature_names):
                results["models_trained"].append("TrendFollowing")
                results["accuracies"]["TrendFollowing"] = self.trend_model.accuracy
            
            if self.mean_reversion_model.train(train_features, train_labels, feature_names):
                results["models_trained"].append("MeanReversion")
                results["accuracies"]["MeanReversion"] = self.mean_reversion_model.accuracy
            
            if self.pattern_model.train(features, labels, feature_names):
                results["models_trained"].append("PatternRecognition")
                results["accuracies"]["PatternRecognition"] = self.pattern_model.accuracy
            
            self.models_trained = len(results["models_trained"]) > 0
            self.last_training_time = datetime.now(timezone.utc)
            results["success"] = self.models_trained
            
            logger.info(f"Model training complete: {results}")
            return results
            
        except Exception as e:
            logger.error(f"Error during model training: {e}")
            results["error"] = str(e)
            return results
    
    async def generate_signal(self, ohlcv_data: Dict[str, np.ndarray], custom_strategy: Dict = None) -> Optional[EnsembleSignal]:
        """
        Generate ensemble trading signal from all models.
        
        Args:
            ohlcv_data: Current market OHLCV data
            custom_strategy: Optional custom strategy from Strategy Builder
        
        Returns:
            EnsembleSignal combining all model predictions
        """
        try:
            # Create features
            features, feature_names = FeatureEngineering.create_features(ohlcv_data)
            if len(features) < 10:
                return None
            
            # Get latest features
            latest_features = features[-1]
            
            # Detect market regime
            self.current_regime = self.detect_market_regime(latest_features, feature_names)
            
            # Collect signals from all models
            signals = []
            
            # Trend following signal
            if self.trend_model.is_trained:
                trend_signal = self.trend_model.predict(latest_features)
                if trend_signal:
                    signals.append(trend_signal)
            
            # Mean reversion signal
            if self.mean_reversion_model.is_trained:
                mr_signal = self.mean_reversion_model.predict(latest_features)
                if mr_signal:
                    signals.append(mr_signal)
            
            # Pattern recognition signal
            if self.pattern_model.is_trained:
                pattern_signal = self.pattern_model.predict(latest_features)
                if pattern_signal:
                    signals.append(pattern_signal)
            
            # Apply custom strategy if provided
            if custom_strategy:
                custom_signal = self._evaluate_custom_strategy(custom_strategy, ohlcv_data, latest_features, feature_names)
                if custom_signal:
                    signals.append(custom_signal)
            
            if not signals:
                return None
            
            # Combine signals using weighted voting
            return self._combine_signals(signals)
            
        except Exception as e:
            logger.error(f"Error generating signal: {e}")
            return None
    
    def _evaluate_custom_strategy(
        self, 
        strategy: Dict, 
        ohlcv_data: Dict[str, np.ndarray],
        features: np.ndarray,
        feature_names: List[str]
    ) -> Optional[MLSignal]:
        """
        Evaluate a custom strategy from the Strategy Builder.
        
        The strategy contains conditions like:
        {
            "name": "My RSI Strategy",
            "conditions": [
                {"indicator": "RSI", "condition": "crosses_below", "value": 30, "signal": "CALL"},
                {"indicator": "RSI", "condition": "crosses_above", "value": 70, "signal": "PUT"}
            ]
        }
        """
        try:
            conditions = strategy.get("conditions", [])
            if not conditions:
                return None
            
            closes = ohlcv_data.get("close", np.array([]))
            
            # Calculate indicators needed for conditions
            indicators = {}
            
            # RSI
            if "rsi_14" in feature_names:
                rsi_idx = feature_names.index("rsi_14")
                indicators["RSI"] = features[rsi_idx]
            
            # BB Position
            if "bb_position" in feature_names:
                bb_idx = feature_names.index("bb_position")
                indicators["BB_POSITION"] = features[bb_idx]
            
            # Check conditions
            call_conditions_met = 0
            put_conditions_met = 0
            total_conditions = len(conditions)
            
            for cond in conditions:
                indicator_name = cond.get("indicator", "").upper()
                condition_type = cond.get("condition", "")
                value = cond.get("value", 0)
                signal = cond.get("signal", "")
                
                indicator_val = indicators.get(indicator_name)
                if indicator_val is None:
                    continue
                
                condition_met = False
                
                if condition_type == "less_than" and indicator_val < value:
                    condition_met = True
                elif condition_type == "greater_than" and indicator_val > value:
                    condition_met = True
                elif condition_type == "crosses_below" and indicator_val < value:
                    condition_met = True
                elif condition_type == "crosses_above" and indicator_val > value:
                    condition_met = True
                
                if condition_met:
                    if signal == "CALL":
                        call_conditions_met += 1
                    elif signal == "PUT":
                        put_conditions_met += 1
            
            # Determine signal based on conditions met
            if call_conditions_met > put_conditions_met and call_conditions_met > 0:
                confidence = (call_conditions_met / total_conditions) * 100
                return MLSignal(
                    direction=TradingDirection.CALL,
                    confidence=confidence,
                    strategy_type=StrategyType.CUSTOM,
                    model_name=f"CustomStrategy:{strategy.get('name', 'Unknown')}",
                    reasoning=f"Custom strategy conditions met: {call_conditions_met}/{total_conditions}",
                    features_used=list(indicators.keys())
                )
            elif put_conditions_met > call_conditions_met and put_conditions_met > 0:
                confidence = (put_conditions_met / total_conditions) * 100
                return MLSignal(
                    direction=TradingDirection.PUT,
                    confidence=confidence,
                    strategy_type=StrategyType.CUSTOM,
                    model_name=f"CustomStrategy:{strategy.get('name', 'Unknown')}",
                    reasoning=f"Custom strategy conditions met: {put_conditions_met}/{total_conditions}",
                    features_used=list(indicators.keys())
                )
            
            return None
            
        except Exception as e:
            logger.error(f"Error evaluating custom strategy: {e}")
            return None
    
    def _combine_signals(self, signals: List[MLSignal]) -> EnsembleSignal:
        """Combine multiple signals into ensemble prediction"""
        
        # Weight signals by confidence and model accuracy
        call_score = 0
        put_score = 0
        hold_score = 0
        
        for signal in signals:
            weight = signal.confidence / 100
            
            if signal.direction == TradingDirection.CALL:
                call_score += weight
            elif signal.direction == TradingDirection.PUT:
                put_score += weight
            else:
                hold_score += weight
        
        total_score = call_score + put_score + hold_score
        
        # Determine final direction
        if call_score > put_score and call_score > hold_score:
            final_direction = TradingDirection.CALL
            final_confidence = (call_score / total_score) * 100 if total_score > 0 else 50
        elif put_score > call_score and put_score > hold_score:
            final_direction = TradingDirection.PUT
            final_confidence = (put_score / total_score) * 100 if total_score > 0 else 50
        else:
            final_direction = TradingDirection.HOLD
            final_confidence = 30
        
        # Calculate consensus
        direction_counts = {
            TradingDirection.CALL: sum(1 for s in signals if s.direction == TradingDirection.CALL),
            TradingDirection.PUT: sum(1 for s in signals if s.direction == TradingDirection.PUT),
            TradingDirection.HOLD: sum(1 for s in signals if s.direction == TradingDirection.HOLD)
        }
        max_agreement = max(direction_counts.values())
        consensus_score = max_agreement / len(signals) if signals else 0
        
        # Determine risk level
        if final_confidence > 75 and consensus_score > 0.7:
            risk_level = "LOW"
        elif final_confidence > 60 and consensus_score > 0.5:
            risk_level = "MEDIUM"
        else:
            risk_level = "HIGH"
        
        # Recommended expiry based on regime
        if self.current_regime in [MarketRegime.TRENDING_UP, MarketRegime.TRENDING_DOWN]:
            recommended_expiry = "1m-5m"
        elif self.current_regime == MarketRegime.VOLATILE:
            recommended_expiry = "30s-1m"
        else:
            recommended_expiry = "1m-3m"
        
        return EnsembleSignal(
            final_direction=final_direction,
            final_confidence=final_confidence,
            consensus_score=consensus_score,
            individual_signals=signals,
            market_regime=self.current_regime,
            risk_level=risk_level,
            recommended_expiry=recommended_expiry
        )
    
    async def record_trade_result(self, signal_id: str, outcome: str) -> Dict[str, Any]:
        """
        Record trade result for continuous learning.
        
        Args:
            signal_id: ID of the original signal
            outcome: "WIN" or "LOSS"
        
        Returns:
            Updated statistics
        """
        try:
            self.total_trades += 1
            if outcome.upper() == "WIN":
                self.winning_trades += 1
            
            self.trade_results.append({
                "signal_id": signal_id,
                "outcome": outcome,
                "timestamp": datetime.now(timezone.utc).isoformat()
            })
            
            win_rate = (self.winning_trades / self.total_trades) * 100 if self.total_trades > 0 else 0
            
            # Trigger retraining if enough new data
            retrain_needed = len(self.trade_results) >= 100 and len(self.trade_results) % 50 == 0
            
            return {
                "success": True,
                "total_trades": self.total_trades,
                "winning_trades": self.winning_trades,
                "win_rate": win_rate,
                "retrain_suggested": retrain_needed
            }
            
        except Exception as e:
            logger.error(f"Error recording trade result: {e}")
            return {"success": False, "error": str(e)}
    
    def get_system_status(self) -> Dict[str, Any]:
        """Get current AI system status"""
        return {
            "models_trained": self.models_trained,
            "last_training_time": self.last_training_time.isoformat() if self.last_training_time else None,
            "total_trades": self.total_trades,
            "winning_trades": self.winning_trades,
            "win_rate": (self.winning_trades / self.total_trades * 100) if self.total_trades > 0 else 0,
            "current_regime": self.current_regime.value,
            "model_accuracies": {
                "trend_following": self.trend_model.accuracy if self.trend_model.is_trained else 0,
                "mean_reversion": self.mean_reversion_model.accuracy if self.mean_reversion_model.is_trained else 0,
                "pattern_recognition": self.pattern_model.accuracy if self.pattern_model.is_trained else 0
            },
            "sklearn_available": SKLEARN_AVAILABLE
        }


# Global instance
enhanced_ai_system = EnhancedAITradingSystem()
